// Sugeneruota automatiskai - ranka neredaguoti.
// Perkurti: powershell -ExecutionPolicy Bypass -File tools\paruosti-nuotraukas.ps1
window.PHOTOS = [
  {"full":"photos/full/People/_DSC0082%20(2).jpg","thumb":"photos/thumb/People/_DSC0082%20(2).jpg","pavadinimas":"Looking out over the bay","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/_DSC0463.jpg","thumb":"photos/thumb/People/_DSC0463.jpg","pavadinimas":"Path between the crosses","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1703},
  {"full":"photos/full/People/April%2030%2C%202019-(Tanzania)-25%20(2).jpg","thumb":"photos/thumb/People/April%2030%2C%202019-(Tanzania)-25%20(2).jpg","pavadinimas":"Portrait in evening light","galerija":"People","atranka":false,"atrankaNr":-1,"w":1992,"h":2492},
  {"full":"photos/full/People/DSC_0007%20(3).jpg","thumb":"photos/thumb/People/DSC_0007%20(3).jpg","pavadinimas":"Two on the wall","galerija":"People","atranka":true,"atrankaNr":8,"w":2560,"h":1941},
  {"full":"photos/full/People/DSC_0007%20(4).jpg","thumb":"photos/thumb/People/DSC_0007%20(4).jpg","pavadinimas":"Wind above the town","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":2048},
  {"full":"photos/full/People/DSC_0080%20(2).jpg","thumb":"photos/thumb/People/DSC_0080%20(2).jpg","pavadinimas":"Fishing harbour","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0108%20(4).jpg","thumb":"photos/thumb/People/DSC_0108%20(4).jpg","pavadinimas":"Steps up the hill","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0137%20(2).jpg","thumb":"photos/thumb/People/DSC_0137%20(2).jpg","pavadinimas":"Dress by the river","galerija":"People","atranka":false,"atrankaNr":-1,"w":2296,"h":2560},
  {"full":"photos/full/People/DSC_0146.jpg","thumb":"photos/thumb/People/DSC_0146.jpg","pavadinimas":"Craftsman in the medina","galerija":"People","atranka":true,"atrankaNr":2,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0153-3.jpg","thumb":"photos/thumb/People/DSC_0153-3.jpg","pavadinimas":"Face to face","galerija":"People","atranka":true,"atrankaNr":18,"w":2048,"h":2560},
  {"full":"photos/full/People/DSC_0178-3.jpg","thumb":"photos/thumb/People/DSC_0178-3.jpg","pavadinimas":"Evening light","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0179%20(2).jpg","thumb":"photos/thumb/People/DSC_0179%20(2).jpg","pavadinimas":"A small flower","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0199.jpg","thumb":"photos/thumb/People/DSC_0199.jpg","pavadinimas":"Behind the steps","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":2342},
  {"full":"photos/full/People/DSC_0291.jpg","thumb":"photos/thumb/People/DSC_0291.jpg","pavadinimas":"Three on the path","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0318%20(2).jpg","thumb":"photos/thumb/People/DSC_0318%20(2).jpg","pavadinimas":"Fish market","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1711},
  {"full":"photos/full/People/DSC_0378%20(2).jpg","thumb":"photos/thumb/People/DSC_0378%20(2).jpg","pavadinimas":"Football on the sand","galerija":"People","atranka":false,"atrankaNr":-1,"w":1888,"h":1261},
  {"full":"photos/full/People/DSC_0519%20(2).jpg","thumb":"photos/thumb/People/DSC_0519%20(2).jpg","pavadinimas":"Along the shore","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0525.jpg","thumb":"photos/thumb/People/DSC_0525.jpg","pavadinimas":"Behind the wheel","galerija":"People","atranka":false,"atrankaNr":-1,"w":1990,"h":1836},
  {"full":"photos/full/People/DSC_0585%20(2).jpg","thumb":"photos/thumb/People/DSC_0585%20(2).jpg","pavadinimas":"Greeting","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":2048},
  {"full":"photos/full/People/DSC_0591.jpg","thumb":"photos/thumb/People/DSC_0591.jpg","pavadinimas":"Before the ceremony","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":2099},
  {"full":"photos/full/People/DSC_0606%20(2).jpg","thumb":"photos/thumb/People/DSC_0606%20(2).jpg","pavadinimas":"Tea with a view","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0617.jpg","thumb":"photos/thumb/People/DSC_0617.jpg","pavadinimas":"By the lake","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/DSC_0660.jpg","thumb":"photos/thumb/People/DSC_0660.jpg","pavadinimas":"Under the tree","galerija":"People","atranka":false,"atrankaNr":-1,"w":2056,"h":2560},
  {"full":"photos/full/People/DSC_0683.jpg","thumb":"photos/thumb/People/DSC_0683.jpg","pavadinimas":"Clear water","galerija":"People","atranka":true,"atrankaNr":19,"w":2560,"h":1661},
  {"full":"photos/full/People/DSC_0774.jpg","thumb":"photos/thumb/People/DSC_0774.jpg","pavadinimas":"Evening on the hill","galerija":"People","atranka":true,"atrankaNr":14,"w":2560,"h":1570},
  {"full":"photos/full/People/DSC_0776%20(2).jpg","thumb":"photos/thumb/People/DSC_0776%20(2).jpg","pavadinimas":"Together at sunset","galerija":"People","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/People/February%2009%2C%202019-(Tanzania)-13%20(2).jpg","thumb":"photos/thumb/People/February%2009%2C%202019-(Tanzania)-13%20(2).jpg","pavadinimas":"Drums by the fire","galerija":"People","atranka":true,"atrankaNr":11,"w":2560,"h":1612},
  {"full":"photos/full/People/February%2013%2C%202019-(Tanzania)-10.jpg","thumb":"photos/thumb/People/February%2013%2C%202019-(Tanzania)-10.jpg","pavadinimas":"Fisherman at low tide","galerija":"People","atranka":true,"atrankaNr":3,"w":2560,"h":1818},
  {"full":"photos/full/Travel/_DSC0004.jpg","thumb":"photos/thumb/Travel/_DSC0004.jpg","pavadinimas":"Zabriskie Point","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0031.jpg","thumb":"photos/thumb/Travel/_DSC0031.jpg","pavadinimas":"Motorcycles in the desert","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2138,"h":1427},
  {"full":"photos/full/Travel/_DSC0036.jpg","thumb":"photos/thumb/Travel/_DSC0036.jpg","pavadinimas":"Desert highway","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0046.jpg","thumb":"photos/thumb/Travel/_DSC0046.jpg","pavadinimas":"Roadside stop","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0058.jpg","thumb":"photos/thumb/Travel/_DSC0058.jpg","pavadinimas":"Low tide","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0073%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0073%20(2).jpg","pavadinimas":"Town by the sea","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0101%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0101%20(2).jpg","pavadinimas":"Challenger","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0105.jpg","thumb":"photos/thumb/Travel/_DSC0105.jpg","pavadinimas":"Road through the valley","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0162-2.jpg","thumb":"photos/thumb/Travel/_DSC0162-2.jpg","pavadinimas":"Mountains in the mirror","galerija":"Travel","atranka":true,"atrankaNr":13,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0220.jpg","thumb":"photos/thumb/Travel/_DSC0220.jpg","pavadinimas":"Reflection in the pasture","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0233%20(3).jpg","thumb":"photos/thumb/Travel/_DSC0233%20(3).jpg","pavadinimas":"Bay below the mountains","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1696},
  {"full":"photos/full/Travel/_DSC0298.jpg","thumb":"photos/thumb/Travel/_DSC0298.jpg","pavadinimas":"Plymouth GTX","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1760},
  {"full":"photos/full/Travel/_DSC0320%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0320%20(2).jpg","pavadinimas":"Pasture above the rooftops","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0333.jpg","thumb":"photos/thumb/Travel/_DSC0333.jpg","pavadinimas":"Golden Gate and freighter","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1730},
  {"full":"photos/full/Travel/_DSC0353.jpg","thumb":"photos/thumb/Travel/_DSC0353.jpg","pavadinimas":"Golden Gate","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1873},
  {"full":"photos/full/Travel/_DSC0355.jpg","thumb":"photos/thumb/Travel/_DSC0355.jpg","pavadinimas":"Waves on the rocks","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1515},
  {"full":"photos/full/Travel/_DSC0390%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0390%20(2).jpg","pavadinimas":"Flowers above the harbour","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0412%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0412%20(2).jpg","pavadinimas":"Tree by the wall","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1806},
  {"full":"photos/full/Travel/_DSC0424.jpg","thumb":"photos/thumb/Travel/_DSC0424.jpg","pavadinimas":"On the bridge","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1559},
  {"full":"photos/full/Travel/_DSC0427.jpg","thumb":"photos/thumb/Travel/_DSC0427.jpg","pavadinimas":"Statue among ruins","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0433.jpg","thumb":"photos/thumb/Travel/_DSC0433.jpg","pavadinimas":"Reaching up","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0442.jpg","thumb":"photos/thumb/Travel/_DSC0442.jpg","pavadinimas":"Graveyard above the town","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0460%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0460%20(2).jpg","pavadinimas":"Whitby from above","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0461%20(2).jpg","thumb":"photos/thumb/Travel/_DSC0461%20(2).jpg","pavadinimas":"Hill of Crosses","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/_DSC0466.jpg","thumb":"photos/thumb/Travel/_DSC0466.jpg","pavadinimas":"Rosary and angel","galerija":"Travel","atranka":true,"atrankaNr":16,"w":2560,"h":1582},
  {"full":"photos/full/Travel/DSC_0008.jpg","thumb":"photos/thumb/Travel/DSC_0008.jpg","pavadinimas":"Marrakech alley","galerija":"Travel","atranka":true,"atrankaNr":1,"w":2560,"h":1710},
  {"full":"photos/full/Travel/DSC_0011%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0011%20(2).jpg","pavadinimas":"Houses behind the pines","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1725},
  {"full":"photos/full/Travel/DSC_0011%20(4).jpg","thumb":"photos/thumb/Travel/DSC_0011%20(4).jpg","pavadinimas":"Marshrutka","galerija":"Travel","atranka":true,"atrankaNr":6,"w":2560,"h":2048},
  {"full":"photos/full/Travel/DSC_0023%20(3).jpg","thumb":"photos/thumb/Travel/DSC_0023%20(3).jpg","pavadinimas":"Promenade in the haze","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0024%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0024%20(2).jpg","pavadinimas":"Leaves by the fence","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1337},
  {"full":"photos/full/Travel/DSC_0024%20(3).jpg","thumb":"photos/thumb/Travel/DSC_0024%20(3).jpg","pavadinimas":"Town in the valley","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1592},
  {"full":"photos/full/Travel/DSC_0059%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0059%20(2).jpg","pavadinimas":"Harbour in the fog","galerija":"Travel","atranka":true,"atrankaNr":0,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0082.jpg","thumb":"photos/thumb/Travel/DSC_0082.jpg","pavadinimas":"Sunken boat","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0096%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0096%20(2).jpg","pavadinimas":"River bend","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1675},
  {"full":"photos/full/Travel/DSC_0133.jpg","thumb":"photos/thumb/Travel/DSC_0133.jpg","pavadinimas":"Three in a box","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1444},
  {"full":"photos/full/Travel/DSC_0142-2.jpg","thumb":"photos/thumb/Travel/DSC_0142-2.jpg","pavadinimas":"Rally Lada","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0151.jpg","thumb":"photos/thumb/Travel/DSC_0151.jpg","pavadinimas":"Gull by the Tiber","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0210.jpg","thumb":"photos/thumb/Travel/DSC_0210.jpg","pavadinimas":"Sun through branches","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1789},
  {"full":"photos/full/Travel/DSC_0222%20(4).jpg","thumb":"photos/thumb/Travel/DSC_0222%20(4).jpg","pavadinimas":"Road across the Atlas","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1584},
  {"full":"photos/full/Travel/DSC_0274-2.jpg","thumb":"photos/thumb/Travel/DSC_0274-2.jpg","pavadinimas":"Amsterdam canal","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1643},
  {"full":"photos/full/Travel/DSC_0310%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0310%20(2).jpg","pavadinimas":"Two at sunset","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":1010,"h":1029},
  {"full":"photos/full/Travel/DSC_0596.jpg","thumb":"photos/thumb/Travel/DSC_0596.jpg","pavadinimas":"Light over Naples","galerija":"Travel","atranka":true,"atrankaNr":9,"w":2560,"h":1667},
  {"full":"photos/full/Travel/DSC_0726.jpg","thumb":"photos/thumb/Travel/DSC_0726.jpg","pavadinimas":"Sun behind clouds","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_0871%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0871%20(2).jpg","pavadinimas":"Coastline and boat","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1506},
  {"full":"photos/full/Travel/DSC_0880%20(2).jpg","thumb":"photos/thumb/Travel/DSC_0880%20(2).jpg","pavadinimas":"Gulls on the shore","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1332},
  {"full":"photos/full/Travel/DSC_2794.jpg","thumb":"photos/thumb/Travel/DSC_2794.jpg","pavadinimas":"Valley under clouds","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Travel/DSC_2812.jpg","thumb":"photos/thumb/Travel/DSC_2812.jpg","pavadinimas":"Stop in the Alps","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1693},
  {"full":"photos/full/Travel/DSC_2839.jpg","thumb":"photos/thumb/Travel/DSC_2839.jpg","pavadinimas":"Lone sailboat","galerija":"Travel","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0005.jpg","thumb":"photos/thumb/Wildlife/DSC_0005.jpg","pavadinimas":"Marabou over the acacias","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0041-3.jpg","thumb":"photos/thumb/Wildlife/DSC_0041-3.jpg","pavadinimas":"Lion in profile","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1978},
  {"full":"photos/full/Wildlife/DSC_0044.jpg","thumb":"photos/thumb/Wildlife/DSC_0044.jpg","pavadinimas":"Impala in tall grass","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":2090},
  {"full":"photos/full/Wildlife/DSC_0074-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0074-2.jpg","pavadinimas":"Lion asleep","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":2048},
  {"full":"photos/full/Wildlife/DSC_0101%20(3).jpg","thumb":"photos/thumb/Wildlife/DSC_0101%20(3).jpg","pavadinimas":"Two impalas","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2376,"h":2521},
  {"full":"photos/full/Wildlife/DSC_0115-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0115-2.jpg","pavadinimas":"Buffalo herd with egret","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2335,"h":1559},
  {"full":"photos/full/Wildlife/DSC_0118-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0118-2.jpg","pavadinimas":"Black-headed heron","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2193,"h":1463},
  {"full":"photos/full/Wildlife/DSC_0149-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0149-2.jpg","pavadinimas":"Zebras crossing","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1696},
  {"full":"photos/full/Wildlife/DSC_0154-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0154-2.jpg","pavadinimas":"Stripes up close","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2179,"h":2560},
  {"full":"photos/full/Wildlife/DSC_0167-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0167-2.jpg","pavadinimas":"Hippo and swallow","galerija":"Wildlife","atranka":true,"atrankaNr":5,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0171%20(4).jpg","thumb":"photos/thumb/Wildlife/DSC_0171%20(4).jpg","pavadinimas":"Trunks locked","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1909},
  {"full":"photos/full/Wildlife/DSC_0181-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0181-2.jpg","pavadinimas":"Watching from the water","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0198-2%20(2).jpg","thumb":"photos/thumb/Wildlife/DSC_0198-2%20(2).jpg","pavadinimas":"Zebra in the crater","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0203-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0203-2.jpg","pavadinimas":"Zebras below the crater rim","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0206-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0206-2.jpg","pavadinimas":"Zebra in the rain","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2172,"h":1450},
  {"full":"photos/full/Wildlife/DSC_0222%20(3).jpg","thumb":"photos/thumb/Wildlife/DSC_0222%20(3).jpg","pavadinimas":"Elephant herd on the plain","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1545},
  {"full":"photos/full/Wildlife/DSC_0234-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0234-2.jpg","pavadinimas":"Zebra portrait","galerija":"Wildlife","atranka":true,"atrankaNr":10,"w":2473,"h":1651},
  {"full":"photos/full/Wildlife/DSC_0241-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0241-2.jpg","pavadinimas":"Zebra in the mist","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0263%20(2).jpg","thumb":"photos/thumb/Wildlife/DSC_0263%20(2).jpg","pavadinimas":"Elephant behind branches","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2485,"h":1656},
  {"full":"photos/full/Wildlife/DSC_0289.jpg","thumb":"photos/thumb/Wildlife/DSC_0289.jpg","pavadinimas":"Elephant in the grass","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1638},
  {"full":"photos/full/Wildlife/DSC_0294%20(2).jpg","thumb":"photos/thumb/Wildlife/DSC_0294%20(2).jpg","pavadinimas":"Elephant among acacias","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0355-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0355-2.jpg","pavadinimas":"Superb starling","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0393%20(2).jpg","thumb":"photos/thumb/Wildlife/DSC_0393%20(2).jpg","pavadinimas":"Giraffe behind the jeep","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0395.jpg","thumb":"photos/thumb/Wildlife/DSC_0395.jpg","pavadinimas":"Two giraffes","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1438},
  {"full":"photos/full/Wildlife/DSC_0408-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0408-2.jpg","pavadinimas":"Buffalo and egrets","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0443-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0443-2.jpg","pavadinimas":"Bird on lava rock","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":1762,"h":1176},
  {"full":"photos/full/Wildlife/DSC_0445-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0445-2.jpg","pavadinimas":"In the shallows","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2119,"h":1260},
  {"full":"photos/full/Wildlife/DSC_0476.jpg","thumb":"photos/thumb/Wildlife/DSC_0476.jpg","pavadinimas":"Giraffe among acacias","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1642},
  {"full":"photos/full/Wildlife/DSC_0490-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0490-2.jpg","pavadinimas":"Monitor lizard by the track","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":1915,"h":1279},
  {"full":"photos/full/Wildlife/DSC_0502-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0502-2.jpg","pavadinimas":"Goose rising from the water","galerija":"Wildlife","atranka":true,"atrankaNr":12,"w":1942,"h":1296},
  {"full":"photos/full/Wildlife/DSC_0509.jpg","thumb":"photos/thumb/Wildlife/DSC_0509.jpg","pavadinimas":"Herd crossing the road","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1484},
  {"full":"photos/full/Wildlife/DSC_0515%20(2).jpg","thumb":"photos/thumb/Wildlife/DSC_0515%20(2).jpg","pavadinimas":"Carrying a branch","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2334,"h":1919},
  {"full":"photos/full/Wildlife/DSC_0544-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0544-2.jpg","pavadinimas":"Monkey in the leaves","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2103,"h":1404},
  {"full":"photos/full/Wildlife/DSC_0568-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0568-2.jpg","pavadinimas":"Baboon yawning","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0579-2.jpg","thumb":"photos/thumb/Wildlife/DSC_0579-2.jpg","pavadinimas":"Baboon portrait","galerija":"Wildlife","atranka":true,"atrankaNr":17,"w":2560,"h":1978},
  {"full":"photos/full/Wildlife/DSC_0684.jpg","thumb":"photos/thumb/Wildlife/DSC_0684.jpg","pavadinimas":"Family against the light","galerija":"Wildlife","atranka":true,"atrankaNr":7,"w":2560,"h":1663},
  {"full":"photos/full/Wildlife/DSC_0720.jpg","thumb":"photos/thumb/Wildlife/DSC_0720.jpg","pavadinimas":"Two elephants on the crater floor","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1625},
  {"full":"photos/full/Wildlife/DSC_0837.jpg","thumb":"photos/thumb/Wildlife/DSC_0837.jpg","pavadinimas":"Eye to eye","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":2048},
  {"full":"photos/full/Wildlife/DSC_0842.jpg","thumb":"photos/thumb/Wildlife/DSC_0842.jpg","pavadinimas":"Zebra and baboon","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0878.jpg","thumb":"photos/thumb/Wildlife/DSC_0878.jpg","pavadinimas":"Wildebeest on the plain","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0916.jpg","thumb":"photos/thumb/Wildlife/DSC_0916.jpg","pavadinimas":"Zebra yawning","galerija":"Wildlife","atranka":true,"atrankaNr":4,"w":2560,"h":2048},
  {"full":"photos/full/Wildlife/DSC_0928.jpg","thumb":"photos/thumb/Wildlife/DSC_0928.jpg","pavadinimas":"Zebras by the acacia","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2415,"h":1611},
  {"full":"photos/full/Wildlife/DSC_0931.jpg","thumb":"photos/thumb/Wildlife/DSC_0931.jpg","pavadinimas":"By the lake","galerija":"Wildlife","atranka":true,"atrankaNr":15,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0958.jpg","thumb":"photos/thumb/Wildlife/DSC_0958.jpg","pavadinimas":"Wildebeest herd","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709},
  {"full":"photos/full/Wildlife/DSC_0978.jpg","thumb":"photos/thumb/Wildlife/DSC_0978.jpg","pavadinimas":"Gazelle and wildebeest","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2302,"h":1537},
  {"full":"photos/full/Wildlife/DSC_0979.jpg","thumb":"photos/thumb/Wildlife/DSC_0979.jpg","pavadinimas":"Bare acacia","galerija":"Wildlife","atranka":false,"atrankaNr":-1,"w":2560,"h":1709}
];
